### PR TITLE
Refactor getaddrinfo.

### PR DESCRIPTION
**Pull request by take-cheeze**
* Fixing old bugs that was kept unfixed.
* Fixes travis.(Also tests 1.2, 1.3, master)
* Skips `scandir` when file system always return file type `unknown`.
* Add `UV::FS.scandir` which make `UV::FS.readdir` an alias.

### CODE REVIEW

**Comment by mattn** [comment]
Oh, good. Please wait for my checking.

**Comment by mattn** [comment]
Build error on Windows.

https://gist.github.com/eba471dd637c61afc877f6b055e11251

**Comment by mattn** [comment]
Could you please add this?

```diff
diff --git a/src/mrb_uv.c b/src/mrb_uv.c
index 73ab6cf..35a8a08 100644
--- a/src/mrb_uv.c
+++ b/src/mrb_uv.c
@@ -1,3 +1,4 @@
+#define _WIN32_WINNT 0x0600
 #include "mruby/uv.h"
 #include "mrb_uv.h"
 
```

**Comment by mattn** [comment]
LGTM (if you add change I mentioned). Tests passed.

**Comment by take-cheeze** [comment]
Those flags is from:
http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/netdb.h.html
Though I don't think all of them is required so I'll remove them.
Does `_WIN32_WINNT` still required when I removed `AI_NUMERICSERV`, `AI_V4MAPPED`, `AI_ALL`, `AI_ADDRCONFIG`?

**Comment by take-cheeze** [comment]
@mattn Remove 4 constants.

**Comment by mattn** [comment]
>Does _WIN32_WINNT still required when I removed AI_NUMERICSERV, AI_V4MAPPED, AI_ALL, AI_ADDRCONFIG?

If add _WIN32_WINNT >= 0x0600, compilation error is removed. I want to keep it on Windows.

**Comment by take-cheeze** [comment]
@mattn reverted constants remove and added `_WIN32_WINNT` define.

**Comment by mattn** [comment]
Thank you. I'll look it after takoyaki party.

On 9/23/17, Takeshi Watanabe <notifications@github.com> wrote:
> @mattn reverted constants remove and added `_WIN32_WINNT` define.
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/mattn/mruby-uv/pull/77#issuecomment-331619469


-- 
- Yasuhiro Matsumoto

**Comment by take-cheeze** [comment]
🐙

**Comment by mattn** [comment]
Thanks! :octocat:

**Pull request merged**
